spring:
  application:
    name: moment-server
  datasource:
    url: jdbc:mysql://localhost:3306/moment?useSSL=false
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB