spring:
  kafka:
    bootstrap-servers: 192.168.102.47:9091,192.168.102.47:9092,192.168.102.47:9093
    consumer:
      group-id: mygroup
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
# ack 提交方式，直接影响刷盘，建议批次，不建议逐笔. 使用manual时，需要关闭auto commit
      enable-auto-commit: false
    listener:
      ack-mode: manual
app:
  topic: gino.topic