spring:
  kafka:
    bootstrap-servers: 192.168.102.47:9092
    consumer:
      group-id: mygroup
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
app:
  topic: gino.topic