spring:
  kafka:
    bootstrap-servers: 192.168.102.47:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
app:
  topic: gino.topic